baseURL = "https://pawsey-internships.github.io/intro_parallelism_and_workflows/" 
languageCode = "en-us"
theme = "learn"
title = "Introduction to Parallelism and Supercomputing Workflows"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
disableBreadcrumb = false
disableNextPrev = false
themeVariant = "green"
disableLandingPageButton = true
